services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=mammoth,pdf-to-img
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_PATH=/home/node/.n8n/custom-modules/node_modules
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: